<?php

$I = new ApiTester($scenario);
$I->wantTo("Test API call v1/person/Kontakt/: Kontakt OnlyKontakt KontaktByPersonID OnlyKontaktByPersonID KontaktByPersonIDKontaktTyp");
$I->amHttpAuthenticated("admin", "1q2w3");
$I->haveHttpHeader("FHC-API-KEY", "testapikey@fhcomplete.org");
$I->sendGET("v1/person/Kontakt/Kontakt", array("kontakt_id" => "1"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(["error" => 0]);
$I->wait();
$I->sendGET("v1/person/Kontakt/OnlyKontakt", array("kontakt_id" => "1"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(["error" => 0]);
$I->wait();
$I->sendGET("v1/person/Kontakt/KontaktByPersonID", array("person_id" => "1"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(["error" => 0]);
$I->wait();
$I->sendGET("v1/person/Kontakt/OnlyKontaktByPersonID", array("person_id" => "1"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(["error" => 0]);
$I->wait();
$I->sendGET("v1/person/Kontakt/KontaktByPersonIDKontaktTyp", array("person_id" => "1", "kontakttyp" => "1"));
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson(["error" => 0]);
$I->wait();
