INSERT INTO bis.tbl_bundesland VALUES (1,'B','Burgenland');
INSERT INTO bis.tbl_bundesland VALUES (2,'K','Kärnten');
INSERT INTO bis.tbl_bundesland VALUES (3,'NÖ','Niederösterreich');
INSERT INTO bis.tbl_bundesland VALUES (4,'OÖ','Oberösterreich');
INSERT INTO bis.tbl_bundesland VALUES (5,'S','Salzburg');
INSERT INTO bis.tbl_bundesland VALUES (6,'St','Steiermark');
INSERT INTO bis.tbl_bundesland VALUES (7,'T','Tirol');
INSERT INTO bis.tbl_bundesland VALUES (8,'V','Voralberg');
INSERT INTO bis.tbl_bundesland VALUES (9,'W','Wien');
INSERT INTO bis.tbl_bundesland VALUES (10,'EU','Ausland EU');
INSERT INTO bis.tbl_bundesland VALUES (11,'nichtEU','Ausland nicht EU');
