INSERT INTO tbl_nation VALUES ('A', 'I', true, true, 'EU', 'Österreich', 'Österreich', 'Austria', NULL);
INSERT INTO tbl_nation VALUES ('ADN', 'E', NULL, NULL, 'AS', 'Jemen (Süd)', 'Jemen (demokrat. VR/Süd)', 'South Yemen', true);
INSERT INTO tbl_nation VALUES ('AFG', 'E', NULL, NULL, 'AS', 'Afghanistan', 'Afghanistan', 'Afghanistan', NULL);
INSERT INTO tbl_nation VALUES ('AGL', 'E', NULL, NULL, 'AF', 'Angola', 'Angola', 'Angola', NULL);
INSERT INTO tbl_nation VALUES ('AGN', 'E', NULL, NULL, 'AF', 'Guinea (Äquat.)', 'Guinea (Äquatorial-g.)', 'Equatorial Guinea', NULL);
INSERT INTO tbl_nation VALUES ('AL', 'E', NULL, NULL, 'EU', 'Albanien', 'Albanien', 'Albania', NULL);
INSERT INTO tbl_nation VALUES ('AND', 'I', NULL, NULL, 'EU', 'Andorra', 'Andorra', 'Andorra', NULL);
INSERT INTO tbl_nation VALUES ('ARM', 'E', NULL, NULL, 'AS', 'Armenien', 'Armenien', 'Armenia', NULL);
INSERT INTO tbl_nation VALUES ('ASB', 'E', NULL, NULL, 'AS', 'Aserbaidschan', 'Aserbaidschan', 'Azerbaijan', NULL);
INSERT INTO tbl_nation VALUES ('ATB', 'E', NULL, NULL, 'AM', 'Antigua/Barbuda', 'Antigua und Barbuda', 'Antigua and Barbuda', NULL);
INSERT INTO tbl_nation VALUES ('AUS', 'I', NULL, NULL, 'AU', 'Australien', 'Australien', 'Australia', NULL);
INSERT INTO tbl_nation VALUES ('B', 'I', true, true, 'EU', 'Belgien', 'Belgien', 'Belgium', NULL);
INSERT INTO tbl_nation VALUES ('BAN', 'E', NULL, NULL, 'AS', 'Bangladesch', 'Bangladesch', 'Bangladesh', NULL);
INSERT INTO tbl_nation VALUES ('BDS', 'E', NULL, NULL, 'AM', 'Barbados', 'Barbados', 'Barbados', NULL);
INSERT INTO tbl_nation VALUES ('BG', 'H', NULL, NULL, 'EU', 'Bulgarien', 'Bulgarien', 'Bulgaria', NULL);
INSERT INTO tbl_nation VALUES ('BH', 'E', NULL, NULL, 'AM', 'Honduras', 'Honduras', 'Honduras', NULL);
INSERT INTO tbl_nation VALUES ('BHU', 'E', NULL, NULL, 'AS', 'Bhutan', 'Bhutan', 'Bhutan', NULL);
INSERT INTO tbl_nation VALUES ('BLR', 'H', NULL, NULL, 'EU', 'Weißrußland', 'Weißrußland', 'Belarus', NULL);
INSERT INTO tbl_nation VALUES ('BLZ', 'E', NULL, NULL, 'AM', 'Belize', 'Belize', 'Belize', NULL);
INSERT INTO tbl_nation VALUES ('BOL', 'E', NULL, NULL, 'AM', 'Bolivien', 'Bolivien', 'Bolivia', NULL);
INSERT INTO tbl_nation VALUES ('BR', 'E', NULL, NULL, 'AM', 'Brasilien', 'Brasilien', 'Brazil', NULL);
INSERT INTO tbl_nation VALUES ('BRG', 'E', NULL, NULL, 'AM', 'Guyana', 'Guyana', 'Guyana', NULL);
INSERT INTO tbl_nation VALUES ('BRN', 'E', NULL, NULL, 'AS', 'Bahrein', 'Bahrein', 'Bahrain', NULL);
INSERT INTO tbl_nation VALUES ('BRU', 'H', NULL, NULL, 'AS', 'Brunei', 'Brunei', 'Brunei', NULL);
INSERT INTO tbl_nation VALUES ('BS', 'H', NULL, NULL, 'AM', 'Bahamas', 'Bahamas', 'Bahamas', NULL);
INSERT INTO tbl_nation VALUES ('BSH', 'E', NULL, NULL, 'EU', 'Bosnien-Herzeg.', 'Bosnien-Herzegowina', 'Bosnia and Herzegovina', NULL);
INSERT INTO tbl_nation VALUES ('BTS', 'E', NULL, NULL, 'AF', 'Bophutatswana', 'Bophutatswana', 'Bophutatswana', true);
INSERT INTO tbl_nation VALUES ('BUR', 'E', NULL, NULL, 'AS', 'Myanmar (Birma)', 'Myanmar (Birma)', 'Myanmar', NULL);
INSERT INTO tbl_nation VALUES ('C', 'E', NULL, NULL, 'AM', 'Kuba', 'Kuba', 'Cuba', NULL);
INSERT INTO tbl_nation VALUES ('CAM', 'E', NULL, NULL, 'AF', 'Kamerun', 'Kamerun', 'Cameroon', NULL);
INSERT INTO tbl_nation VALUES ('CDN', 'I', NULL, NULL, 'AM', 'Kanada', 'Kanada', 'Canada', NULL);
INSERT INTO tbl_nation VALUES ('CH', 'I', NULL, NULL, 'EU', 'Schweiz', 'Schweiz', 'Switzerland', NULL);
INSERT INTO tbl_nation VALUES ('CHF', 'E', NULL, NULL, 'AS', 'China (VR)', 'China (Volksrepublik)', 'China', NULL);
INSERT INTO tbl_nation VALUES ('CI', 'E', NULL, NULL, 'AF', 'Cote d''Ivoire', 'Cote d''Ivoire', 'Ivory Coast', NULL);
INSERT INTO tbl_nation VALUES ('CL', 'E', NULL, NULL, 'AS', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', NULL);
INSERT INTO tbl_nation VALUES ('CO', 'E', NULL, NULL, 'AM', 'Kolumbien', 'Kolumbien', 'Columbia', NULL);
INSERT INTO tbl_nation VALUES ('CR', 'E', NULL, NULL, 'AM', 'Kostarika', 'Kostarika', 'Costa Rica', NULL);
INSERT INTO tbl_nation VALUES ('CRO', 'E', NULL, NULL, 'EU', 'Kroatien', 'Kroatien', 'Croatia', NULL);
INSERT INTO tbl_nation VALUES ('CS', 'I', NULL, NULL, 'EU', 'Tschechoslowakei', 'Tschechoslowakei', 'Czechoslovakia', true);
INSERT INTO tbl_nation VALUES ('CSK', 'E', NULL, NULL, 'AF', 'Ciskei', 'Ciskei', 'Ciskei', true);
INSERT INTO tbl_nation VALUES ('CY', 'H', NULL, NULL, 'EU', 'Zypern', 'Zypern', 'Cyprus', NULL);
INSERT INTO tbl_nation VALUES ('D', 'I', true, true, 'EU', 'Deutschland', 'Deutschland', 'Germany', NULL);
INSERT INTO tbl_nation VALUES ('DCH', 'E', NULL, NULL, 'AM', 'Dominikan. Rep.', 'Dominikanische Republik', 'Dominican Republic', NULL);
INSERT INTO tbl_nation VALUES ('DDR', 'I', NULL, NULL, 'EU', 'DDR', 'Deutschland (DDR)', 'German Democratic Rep.', true);
INSERT INTO tbl_nation VALUES ('DJI', 'E', NULL, NULL, 'AF', 'Dschibuti', 'Dschibuti', 'Djibouti', NULL);
INSERT INTO tbl_nation VALUES ('DK', 'I', true, true, 'EU', 'Dänemark', 'Dänemark', 'Denmark', NULL);
INSERT INTO tbl_nation VALUES ('DVK', 'E', NULL, NULL, 'AS', 'Korea (Nord)', 'Korea (demokrat. VR/Nord)', 'Korea (democr.P.Republ.)', NULL);
INSERT INTO tbl_nation VALUES ('DY', 'E', NULL, NULL, 'AF', 'Benin', 'Benin', 'Benin', NULL);
INSERT INTO tbl_nation VALUES ('DZ', 'E', NULL, NULL, 'AF', 'Algerien', 'Algerien', 'Algeria', NULL);
INSERT INTO tbl_nation VALUES ('E', 'I', true, true, 'EU', 'Spanien', 'Spanien', 'Spain', NULL);
INSERT INTO tbl_nation VALUES ('EAK', 'E', NULL, NULL, 'AF', 'Kenia', 'Kenia', 'Kenya', NULL);
INSERT INTO tbl_nation VALUES ('EAT', 'E', NULL, NULL, 'AF', 'Tansania', 'Tansania', 'Tanzania', NULL);
INSERT INTO tbl_nation VALUES ('EAU', 'E', NULL, NULL, 'AF', 'Uganda', 'Uganda', 'Uganda', NULL);
INSERT INTO tbl_nation VALUES ('EC', 'E', NULL, NULL, 'AM', 'Ekuador', 'Ekuador', 'Ecuador', NULL);
INSERT INTO tbl_nation VALUES ('ELD', 'H', NULL, NULL, 'EU', 'Estland', 'Estland', 'Estonia', NULL);
INSERT INTO tbl_nation VALUES ('ERI', 'E', NULL, NULL, 'AF', 'Eritrea', 'Eritrea', 'Eritrea', NULL);
INSERT INTO tbl_nation VALUES ('ES', 'E', NULL, NULL, 'AM', 'El Salvador', 'El Salvador', 'El Salvador', NULL);
INSERT INTO tbl_nation VALUES ('ET', 'E', NULL, NULL, 'AF', 'Ägypten', 'Ägypten', 'Egypt', NULL);
INSERT INTO tbl_nation VALUES ('ETH', 'E', NULL, NULL, 'AF', 'Äthiopien', 'Äthiopien', 'Ethiopia', NULL);
INSERT INTO tbl_nation VALUES ('F', 'I', true, true, 'EU', 'Frankreich', 'Frankreich', 'France', NULL);
INSERT INTO tbl_nation VALUES ('FJI', 'E', NULL, NULL, 'AU', 'Fidschi', 'Fidschi', 'Fiji', NULL);
INSERT INTO tbl_nation VALUES ('FL', 'I', NULL, true, 'EU', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', NULL);
INSERT INTO tbl_nation VALUES ('GAB', 'E', NULL, NULL, 'AF', 'Gabun', 'Gabun', 'Gabon', NULL);
INSERT INTO tbl_nation VALUES ('GB', 'I', true, true, 'EU', 'GB u. Nordirland', 'Grossbrit. u. Nordirland', 'Great Britain & N.Ireland', NULL);
INSERT INTO tbl_nation VALUES ('GCA', 'E', NULL, NULL, 'AM', 'Guatemala', 'Guatemala', 'Guatemala', NULL);
INSERT INTO tbl_nation VALUES ('GG', 'E', NULL, NULL, 'AS', 'Georgien', 'Georgien', 'Georgia', NULL);
INSERT INTO tbl_nation VALUES ('GH', 'E', NULL, NULL, 'AF', 'Ghana', 'Ghana', 'Ghana', NULL);
INSERT INTO tbl_nation VALUES ('GN', 'E', NULL, NULL, 'AF', 'Guinea', 'Guinea', 'Guinea', NULL);
INSERT INTO tbl_nation VALUES ('GNB', 'E', NULL, NULL, 'AF', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', NULL);
INSERT INTO tbl_nation VALUES ('GR', 'I', true, true, 'EU', 'Griechenland', 'Griechenland', 'Greece', NULL);
INSERT INTO tbl_nation VALUES ('H', 'H', NULL, NULL, 'EU', 'Ungarn', 'Ungarn', 'Hungary', NULL);
INSERT INTO tbl_nation VALUES ('HV', 'E', NULL, NULL, 'AF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', NULL);
INSERT INTO tbl_nation VALUES ('I', 'I', true, true, 'EU', 'Italien', 'Italien', 'Italy', NULL);
INSERT INTO tbl_nation VALUES ('IL', 'H', NULL, NULL, 'AS', 'Israel', 'Israel', 'Israel', NULL);
INSERT INTO tbl_nation VALUES ('IND', 'E', NULL, NULL, 'AS', 'Indien', 'Indien', 'India', NULL);
INSERT INTO tbl_nation VALUES ('IR', 'E', NULL, NULL, 'AS', 'Iran', 'Iran', 'Iran', NULL);
INSERT INTO tbl_nation VALUES ('IRL', 'I', true, true, 'EU', 'Irland', 'Irland', 'Ireland', NULL);
INSERT INTO tbl_nation VALUES ('IRQ', 'E', NULL, NULL, 'AS', 'Irak', 'Irak', 'Iraq', NULL);
INSERT INTO tbl_nation VALUES ('IS', 'I', NULL, true, 'EU', 'Island', 'Island', 'Iceland', NULL);
INSERT INTO tbl_nation VALUES ('IST', 'I', true, true, 'EU', 'Italien(S-Tirol)', 'Italien (Südtirol)', 'Italy', NULL);
INSERT INTO tbl_nation VALUES ('J', 'I', NULL, NULL, 'AS', 'Japan', 'Japan', 'Japan', NULL);
INSERT INTO tbl_nation VALUES ('JA', 'E', NULL, NULL, 'AM', 'Jamaika', 'Jamaika', 'Jamaica', NULL);
INSERT INTO tbl_nation VALUES ('JEM', 'E', NULL, NULL, 'AS', 'Jemen', 'Jemen', 'Yemen', NULL);
INSERT INTO tbl_nation VALUES ('JOR', 'E', NULL, NULL, 'AS', 'Jordanien', 'Jordanien', 'Jordan', NULL);
INSERT INTO tbl_nation VALUES ('KAS', 'E', NULL, NULL, 'AS', 'Kasachstan', 'Kasachstan', 'Kazakhstan', NULL);
INSERT INTO tbl_nation VALUES ('KIR', 'E', NULL, NULL, 'AU', 'Kiribati', 'Kiribati', 'Kiribati', NULL);
INSERT INTO tbl_nation VALUES ('KM', 'E', NULL, NULL, 'AF', 'Komoren', 'Komoren', 'Comoros', NULL);
INSERT INTO tbl_nation VALUES ('KRG', 'E', NULL, NULL, 'AS', 'Kirgistan', 'Kirgistan', 'Kyrgyztan', NULL);
INSERT INTO tbl_nation VALUES ('KT', 'H', NULL, NULL, 'AS', 'Kuwait', 'Kuwait', 'Kuwait', NULL);
INSERT INTO tbl_nation VALUES ('KV', 'E', NULL, NULL, 'AF', 'Kap Verde', 'Kap Verde', 'Cap Verde', NULL);
INSERT INTO tbl_nation VALUES ('L', 'I', true, true, 'EU', 'Luxemburg', 'Luxemburg', 'Luxembourg', NULL);
INSERT INTO tbl_nation VALUES ('LAO', 'E', NULL, NULL, 'AS', 'Laos', 'Laos', 'Laos', NULL);
INSERT INTO tbl_nation VALUES ('LB', 'E', NULL, NULL, 'AF', 'Liberia', 'Liberia', 'Liberia', NULL);
INSERT INTO tbl_nation VALUES ('LIT', 'H', NULL, NULL, 'EU', 'Litauen', 'Litauen', 'Lithuania', NULL);
INSERT INTO tbl_nation VALUES ('LLD', 'H', NULL, NULL, 'EU', 'Lettland', 'Lettland', 'Latvia', NULL);
INSERT INTO tbl_nation VALUES ('LS', 'E', NULL, NULL, 'AF', 'Lesotho', 'Lesotho', 'Lesotho', NULL);
INSERT INTO tbl_nation VALUES ('LT', 'H', NULL, NULL, 'AF', 'Libyen', 'Libyen', 'Libya', NULL);
INSERT INTO tbl_nation VALUES ('M', 'E', NULL, NULL, 'EU', 'Malta', 'Malta', 'Malta', NULL);
INSERT INTO tbl_nation VALUES ('MA', 'E', NULL, NULL, 'AF', 'Marokko', 'Marokko', 'Morocco', NULL);
INSERT INTO tbl_nation VALUES ('MAL', 'E', NULL, NULL, 'AS', 'Malaysia', 'Malaysia', 'Malaysia', NULL);
INSERT INTO tbl_nation VALUES ('MAZ', 'E', NULL, NULL, 'EU', 'Mazedonien', 'Mazedonien (eh.Jug.Rep.)', 'Macedonia', NULL);
INSERT INTO tbl_nation VALUES ('MBK', 'E', NULL, NULL, 'AF', 'Mosambik', 'Mosambik', 'Mozambique', NULL);
INSERT INTO tbl_nation VALUES ('MC', 'I', NULL, NULL, 'EU', 'Monaco', 'Monaco', 'Monaco', NULL);
INSERT INTO tbl_nation VALUES ('MDV', 'E', NULL, NULL, 'AS', 'Malediven', 'Malediven', 'Maldives', NULL);
INSERT INTO tbl_nation VALUES ('MEX', 'E', NULL, NULL, 'AM', 'Mexiko', 'Mexiko', 'Mexico', NULL);
INSERT INTO tbl_nation VALUES ('MGL', 'E', NULL, NULL, 'AS', 'Mongolei', 'Mongolei', 'Mongolia', NULL);
INSERT INTO tbl_nation VALUES ('MIK', 'E', NULL, NULL, 'AU', 'Mikronesien', 'Mikronesien', 'Micronesia', NULL);
INSERT INTO tbl_nation VALUES ('MLD', 'E', NULL, NULL, 'EU', 'Moldova', 'Moldova', 'Moldova', NULL);
INSERT INTO tbl_nation VALUES ('MS', 'E', NULL, NULL, 'AF', 'Mauritius', 'Mauritius', 'Mauritius', NULL);
INSERT INTO tbl_nation VALUES ('MSH', 'E', NULL, NULL, 'AU', 'Marshallinseln', 'Marshallinseln', 'Marshall Islands', NULL);
INSERT INTO tbl_nation VALUES ('MW', 'E', NULL, NULL, 'AF', 'Malawi', 'Malawi', 'Malawi', NULL);
INSERT INTO tbl_nation VALUES ('N', 'I', NULL, true, 'EU', 'Norwegen', 'Norwegen', 'Norway', NULL);
INSERT INTO tbl_nation VALUES ('NAM', 'E', NULL, NULL, 'AF', 'Namibia', 'Namibia', 'Namibia', NULL);
INSERT INTO tbl_nation VALUES ('NEP', 'E', NULL, NULL, 'AS', 'Nepal', 'Nepal', 'Nepal', NULL);
INSERT INTO tbl_nation VALUES ('NIC', 'E', NULL, NULL, 'AM', 'Nikaragua', 'Nikaragua', 'Nicaragua', NULL);
INSERT INTO tbl_nation VALUES ('NIG', 'E', NULL, NULL, 'AF', 'Niger', 'Niger', 'Niger', NULL);
INSERT INTO tbl_nation VALUES ('NL', 'I', true, true, 'EU', 'Niederlande', 'Niederlande', 'Netherlands', NULL);
INSERT INTO tbl_nation VALUES ('NR', 'E', NULL, NULL, 'AU', 'Nauru', 'Nauru', 'Nauru', NULL);
INSERT INTO tbl_nation VALUES ('NZ', 'I', NULL, NULL, 'AU', 'Neuseeland', 'Neuseeland', 'New Zealand', NULL);
INSERT INTO tbl_nation VALUES ('OMN', 'E', NULL, NULL, 'AS', 'Oman', 'Oman', 'Oman', NULL);
INSERT INTO tbl_nation VALUES ('P', 'I', true, true, 'EU', 'Portugal', 'Portugal', 'Portugal', NULL);
INSERT INTO tbl_nation VALUES ('PA', 'E', NULL, NULL, 'AM', 'Panama', 'Panama', 'Panama', NULL);
INSERT INTO tbl_nation VALUES ('PAK', 'E', NULL, NULL, 'AS', 'Pakistan', 'Pakistan', 'Pakistan', NULL);
INSERT INTO tbl_nation VALUES ('PE', 'E', NULL, NULL, 'AM', 'Peru', 'Peru', 'Peru', NULL);
INSERT INTO tbl_nation VALUES ('PI', 'E', NULL, NULL, 'AS', 'Philippinen', 'Philippinen', 'Philippines', NULL);
INSERT INTO tbl_nation VALUES ('PL', 'H', NULL, NULL, 'EU', 'Polen', 'Polen', 'Poland', NULL);
INSERT INTO tbl_nation VALUES ('PNG', 'E', NULL, NULL, 'AU', 'Papua-Neuguinea', 'Papua-Neuguinea', 'Papua New Guinea', NULL);
INSERT INTO tbl_nation VALUES ('PY', 'E', NULL, NULL, 'AM', 'Paraguay', 'Paraguay', 'Paraguay', NULL);
INSERT INTO tbl_nation VALUES ('QTR', 'H', NULL, NULL, 'AS', 'Katar', 'Katar', 'Qatar', NULL);
INSERT INTO tbl_nation VALUES ('R', 'H', NULL, NULL, 'EU', 'Rumänien', 'Rumänien', 'Romania', NULL);
INSERT INTO tbl_nation VALUES ('RA', 'E', NULL, NULL, 'AM', 'Argentinien', 'Argentinien', 'Argentina', NULL);
INSERT INTO tbl_nation VALUES ('RB', 'E', NULL, NULL, 'AF', 'Botswana', 'Botswana', 'Botswana', NULL);
INSERT INTO tbl_nation VALUES ('RC', 'H', NULL, NULL, 'AS', 'China (Taiwan)', 'China (Republik/Taiwan)', 'Taiwan', NULL);
INSERT INTO tbl_nation VALUES ('RCA', 'E', NULL, NULL, 'AF', 'Zentralafr. Rep.', 'Zentralafrikan. Republik', 'Central African Republic', NULL);
INSERT INTO tbl_nation VALUES ('RCB', 'E', NULL, NULL, 'AF', 'Kongo (Republik)', 'Kongo (Republik)', 'Congo (Rep.)', NULL);
INSERT INTO tbl_nation VALUES ('RCH', 'E', NULL, NULL, 'AM', 'Chile', 'Chile', 'Chile', NULL);
INSERT INTO tbl_nation VALUES ('RH', 'E', NULL, NULL, 'AM', 'Haiti', 'Haiti', 'Haiti', NULL);
INSERT INTO tbl_nation VALUES ('RI', 'E', NULL, NULL, 'AS', 'Indonesien', 'Indonesien', 'Indonesia', NULL);
INSERT INTO tbl_nation VALUES ('RIM', 'E', NULL, NULL, 'AF', 'Mauretanien', 'Mauretanien', 'Mauritania', NULL);
INSERT INTO tbl_nation VALUES ('RL', 'E', NULL, NULL, 'AS', 'Libanon', 'Libanon', 'Lebanon', NULL);
INSERT INTO tbl_nation VALUES ('RM', 'E', NULL, NULL, 'AF', 'Madagaskar', 'Madagaskar', 'Madagascar', NULL);
INSERT INTO tbl_nation VALUES ('RMM', 'E', NULL, NULL, 'AF', 'Mali', 'Mali', 'Mali', NULL);
INSERT INTO tbl_nation VALUES ('ROK', 'H', NULL, NULL, 'AS', 'Korea (Süd)', 'Korea (Republik/Süd)', 'Republic of Korea', NULL);
INSERT INTO tbl_nation VALUES ('RSF', 'H', NULL, NULL, 'EU', 'Rußland', 'Rußland', 'Russian Federation', NULL);
INSERT INTO tbl_nation VALUES ('RSM', 'I', NULL, NULL, 'EU', 'San Marino', 'San Marino', 'San Marino', NULL);
INSERT INTO tbl_nation VALUES ('RSR', 'E', NULL, NULL, 'AF', 'Simbabwe', 'Simbabwe', 'Zimbabwe', NULL);
INSERT INTO tbl_nation VALUES ('RU', 'E', NULL, NULL, 'AF', 'Burundi', 'Burundi', 'Burundi', NULL);
INSERT INTO tbl_nation VALUES ('RWA', 'E', NULL, NULL, 'AF', 'Rwanda', 'Rwanda', 'Rwanda', NULL);
INSERT INTO tbl_nation VALUES ('S', 'I', true, true, 'EU', 'Schweden', 'Schweden', 'Sweden', NULL);
INSERT INTO tbl_nation VALUES ('SA', 'E', NULL, NULL, 'AS', 'Saudi-Arabien', 'Saudi-Arabien', 'Saudi Arabia', NULL);
INSERT INTO tbl_nation VALUES ('SCN', 'E', NULL, NULL, 'AM', 'St.Kitts / Nevis', 'Sankt Kitts und Nevis', 'Saint Kitts and Nevis', NULL);
INSERT INTO tbl_nation VALUES ('SD', 'E', NULL, NULL, 'AF', 'Swasiland', 'Swasiland', 'Swaziland', NULL);
INSERT INTO tbl_nation VALUES ('SF', 'I', true, true, 'EU', 'Finnland', 'Finnland', 'Finland', NULL);
INSERT INTO tbl_nation VALUES ('SGP', 'H', NULL, NULL, 'AS', 'Singapur', 'Singapur', 'Singapore', NULL);
INSERT INTO tbl_nation VALUES ('SHR', 'E', NULL, NULL, 'AF', 'Sahara', 'Sahara', 'Sahara', NULL);
INSERT INTO tbl_nation VALUES ('SLM', 'E', NULL, NULL, 'AU', 'Salomonen', 'Salomonen', 'Salomon Islands', NULL);
INSERT INTO tbl_nation VALUES ('SLO', 'E', NULL, NULL, 'EU', 'Slowenien', 'Slowenien', 'Slovenia', NULL);
INSERT INTO tbl_nation VALUES ('SME', 'E', NULL, NULL, 'AM', 'Surinam', 'Surinam', 'Suriname', NULL);
INSERT INTO tbl_nation VALUES ('SN', 'E', NULL, NULL, 'AF', 'Senegal', 'Senegal', 'Senegal', NULL);
INSERT INTO tbl_nation VALUES ('SP', 'E', NULL, NULL, 'AF', 'Somalia', 'Somalia', 'Somalia', NULL);
INSERT INTO tbl_nation VALUES ('SQ', 'H', NULL, NULL, 'EU', 'Slowakei', 'Slowakei', 'Slovakia', NULL);
INSERT INTO tbl_nation VALUES ('STP', 'E', NULL, NULL, 'AF', 'Sao Tome/Princ.', 'Sao Tome und Principe', 'Sao Tome and Principe', NULL);
INSERT INTO tbl_nation VALUES ('SU', 'I', NULL, NULL, 'EU', 'Sowjetunion', 'Sowjetunion', 'Soviet Union', true);
INSERT INTO tbl_nation VALUES ('SUD', 'E', NULL, NULL, 'AF', 'Sudan', 'Sudan', 'Sudan', NULL);
INSERT INTO tbl_nation VALUES ('SY', 'E', NULL, NULL, 'AF', 'Seychellen', 'Seychellen', 'Seychelles', NULL);
INSERT INTO tbl_nation VALUES ('SYR', 'E', NULL, NULL, 'AS', 'Syrien', 'Syrien', 'Syria', NULL);
INSERT INTO tbl_nation VALUES ('T', 'E', NULL, NULL, 'AS', 'Thailand', 'Thailand', 'Thailand', NULL);
INSERT INTO tbl_nation VALUES ('TA', 'E', NULL, NULL, 'AU', 'Tonga', 'Tonga', 'Tonga', NULL);
INSERT INTO tbl_nation VALUES ('TCH', 'H', NULL, NULL, 'EU', 'Tschechien', 'Tschechien', 'Czech Republic', NULL);
INSERT INTO tbl_nation VALUES ('TD', 'E', NULL, NULL, 'AF', 'Tschad', 'Tschad', 'Chad', NULL);
INSERT INTO tbl_nation VALUES ('TDS', 'E', NULL, NULL, 'AS', 'Tadschikistan', 'Tadschikistan', 'Tajikistan', NULL);
INSERT INTO tbl_nation VALUES ('TG', 'E', NULL, NULL, 'AF', 'Togo', 'Togo', 'Togo', NULL);
INSERT INTO tbl_nation VALUES ('TKM', 'E', NULL, NULL, 'AS', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', NULL);
INSERT INTO tbl_nation VALUES ('TN', 'E', NULL, NULL, 'AF', 'Tunesien', 'Tunesien', 'Tunesia', NULL);
INSERT INTO tbl_nation VALUES ('TR', 'E', NULL, NULL, 'EU', 'Türkei', 'Türkei', 'Turkey', NULL);
INSERT INTO tbl_nation VALUES ('TSK', 'E', NULL, NULL, 'AF', 'Transkei', 'Transkei', 'Transkei', true);
INSERT INTO tbl_nation VALUES ('TT', 'E', NULL, NULL, 'AM', 'Trinidad/Tobago', 'Trinidad und Tobago', 'Trinidad & Tobago', NULL);
INSERT INTO tbl_nation VALUES ('TVL', 'E', NULL, NULL, 'AU', 'Tuvalu', 'Tuvalu', 'Tuvalu', NULL);
INSERT INTO tbl_nation VALUES ('U', 'E', NULL, NULL, 'AM', 'Uruguay', 'Uruguay', 'Uruguay', NULL);
INSERT INTO tbl_nation VALUES ('UBK', 'E', NULL, NULL, 'AS', 'Usbekistan', 'Usbekistan', 'Uzbekistan', NULL);
INSERT INTO tbl_nation VALUES ('UKR', 'H', NULL, NULL, 'EU', 'Ukraine', 'Ukraine', 'Ukraine', NULL);
INSERT INTO tbl_nation VALUES ('USA', 'I', NULL, NULL, 'AM', 'USA', 'Vereinigte St. v. Amerika', 'United States of America', NULL);
INSERT INTO tbl_nation VALUES ('V', 'I', NULL, NULL, 'EU', 'Vatikan', 'Vatikan', 'Vatican', NULL);
INSERT INTO tbl_nation VALUES ('VDA', 'E', NULL, NULL, 'AF', 'Venda', 'Venda', 'Venda', true);
INSERT INTO tbl_nation VALUES ('VE', 'H', NULL, NULL, 'AS', 'V. arab. Emirate', 'Vereinigte arab. Emirate', 'United Arab Emirates', NULL);
INSERT INTO tbl_nation VALUES ('VN', 'E', NULL, NULL, 'AS', 'Vietnam', 'Vietnam', 'Viet Nam', NULL);
INSERT INTO tbl_nation VALUES ('VTU', 'E', NULL, NULL, 'AU', 'Vanuatu', 'Vanuatu', 'Vanuatu', NULL);
INSERT INTO tbl_nation VALUES ('WAG', 'E', NULL, NULL, 'AF', 'Gambia', 'Gambia', 'Gambia', NULL);
INSERT INTO tbl_nation VALUES ('WAL', 'E', NULL, NULL, 'AF', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', NULL);
INSERT INTO tbl_nation VALUES ('WAN', 'E', NULL, NULL, 'AF', 'Nigeria', 'Nigeria', 'Nigeria', NULL);
INSERT INTO tbl_nation VALUES ('WD', 'E', NULL, NULL, 'AM', 'Dominica', 'Dominica', 'Dominica', NULL);
INSERT INTO tbl_nation VALUES ('WG', 'E', NULL, NULL, 'AM', 'Grenada', 'Grenada', 'Grenada', NULL);
INSERT INTO tbl_nation VALUES ('WL', 'E', NULL, NULL, 'AM', 'Sankt Lucia', 'Sankt Lucia', 'Saint Lucia', NULL);
INSERT INTO tbl_nation VALUES ('WS', 'E', NULL, NULL, 'AU', 'Samoa', 'Samoa', 'Samoa', NULL);
INSERT INTO tbl_nation VALUES ('WV', 'E', NULL, NULL, 'AM', 'St.Vincent/Gren.', 'Sankt Vincent/Grenadinen', 'Saint Vincent/Grenadines', NULL);
INSERT INTO tbl_nation VALUES ('XXX', 'X', NULL, NULL, NULL, 'Stbg. ungeklärt', 'Stbg. ungeklärt', 'unclear', NULL);
INSERT INTO tbl_nation VALUES ('YU', 'E', NULL, NULL, 'EU', 'Jugoslawien', 'Jugoslawien (und Kosovo)', 'Yugoslavia', NULL);
INSERT INTO tbl_nation VALUES ('YV', 'E', NULL, NULL, 'AM', 'Venezuela', 'Venezuela', 'Venezuela', NULL);
INSERT INTO tbl_nation VALUES ('Z', 'E', NULL, NULL, 'AF', 'Sambia', 'Sambia', 'Zambia', NULL);
INSERT INTO tbl_nation VALUES ('ZA', 'E', NULL, NULL, 'AF', 'Südafrika', 'Südafrika', 'South Africa', NULL);
INSERT INTO tbl_nation VALUES ('ZR', 'E', NULL, NULL, 'AF', 'Kongo (Dem.Rep.)', 'Kongo (Demokrat.Republik)', 'Republic of the Congo', NULL);
INSERT INTO tbl_nation VALUES ('ZZZ', 'Z', NULL, NULL, NULL, 'Staatenlos', 'Staatenlos', 'stateless', NULL);
INSERT INTO tbl_nation VALUES ('PAL', 'E', NULL, NULL, 'AS', 'Palau Inseln', 'Palau Inseln', 'Palau Islands', NULL);
INSERT INTO tbl_nation VALUES ('PST', 'E', NULL, NULL, 'AS', 'Palästina', 'Palästina', 'Palestine', NULL);
INSERT INTO tbl_nation VALUES ('NU', 'E', NULL, NULL, 'AU', 'Niue', 'Niue', 'Niue', NULL);
INSERT INTO tbl_nation VALUES ('K', 'E', NULL, NULL, 'AS', 'Kambodscha', 'Königreich Kambodscha', 'Cambodia', NULL);
INSERT INTO tbl_nation VALUES ('SB', 'I', NULL, NULL, 'EU', 'Serbien', 'Republik Serbien', 'Republic of Serbia', NULL);
INSERT INTO tbl_nation VALUES ('SBM', 'I', NULL, NULL, 'EU', 'Serbien/Montenegro', 'Serbien/Montenegro', 'Serbia/Montenegro', NULL);
INSERT INTO tbl_nation VALUES ('MO', 'I', NULL, NULL, 'EU', 'Montenegro', 'Republik Montenegro', 'Republic of Montenegro', NULL);


