<?php

/**
 * FH-Complete
 *
 * @package		FHC-Helper
 * @author		FHC-Team
 * @copyright	Copyright (c) 2016 fhcomplete.org
 * @license		GPLv3
 * @since		Version 1.0.0
 */

/**
 * FHC Helper
 *
 * @subpackage	Helpers
 * @category	Helpers
 */

if (! defined('BASEPATH')) exit('No direct script access allowed');

// ------------------------------------------------------------------------
// Functions needed in the view FHC-Header
// ------------------------------------------------------------------------

/**
 * Send single Mail with Sancho Design and Layout.
 * @param string $vorlage_kurzbz Name of the template for specific mail content.
 * @param array $vorlage_data Associative array with specific mail content variables
 *  to be replaced in the content template.
 * @param string $to Email-adress.
 * @param string $subject Subject of mail.
 * @param string $headerImg	Filename of the specific Sancho header image.
 * @param string $cc Sets CC of mail.
 * @param string $bcc Sets BCC of mail.
 * @return void
 */
function sendSanchoMail($vorlage_kurzbz, $vorlage_data, $to, $subject, $headerImg = '', $footerImg = '', $from = null, $cc = null, $bcc = null)
{
	$ci =& get_instance();
	$ci->load->library('MailLib');

	$embeddedImages = array();
	$_from = 'noreply@' . DOMAIN;
	$sancho_mail_config = $ci->config->item('mail');

	if ($from == null && isset($sancho_mail_config['sancho_mail_default_sender']) && $sancho_mail_config['sancho_mail_default_sender'])
	{
		$_from = $sancho_mail_config['sancho_mail_default_sender'] . '@' . DOMAIN;
	}

	if (isset($sancho_mail_config['sancho_mail_use_images']) && $sancho_mail_config['sancho_mail_use_images'])
	{
		$sanchoHeader_img = '';
		$sanchoFooter_img = '';

		if (isset($headerImg) && $headerImg != '')
		{
			// use provided header image
			$sanchoHeader_img = $headerImg;
		}
		elseif (isset($sancho_mail_config['sancho_mail_header_img']) && $sancho_mail_config['sancho_mail_header_img'])
		{
			// use default header image
			$sanchoHeader_img = $sancho_mail_config['sancho_mail_header_img'];
		}

		if (isset($footerImg) && $footerImg != '')
		{
			// use provided footer image
			$sanchoFooter_img = $footerImg;
		}
		elseif (isset($sancho_mail_config['sancho_mail_footer_img']) && $sancho_mail_config['sancho_mail_footer_img'])
		{
			// use default footer image
			$sanchoFooter_img =  $sancho_mail_config['sancho_mail_footer_img'];
		}

		// add image file paths
		if (isset($sancho_mail_config['sancho_mail_img_path']))
		{
			if ($sanchoHeader_img != '')
			{
				$sanchoHeader_img = $sancho_mail_config['sancho_mail_img_path'].$sanchoHeader_img;
			}

			if ($sanchoFooter_img != '')
			{
				$sanchoFooter_img = $sancho_mail_config['sancho_mail_img_path'].$sanchoFooter_img;
			}
		}

		// Attach header and footer
		$embeddedImages[] = array('file_name' => $sanchoHeader_img, 'cid' => 'sancho_header');
		$embeddedImages[] = array('file_name' => $sanchoFooter_img, 'cid' => 'sancho_footer');
	}

	// Set specific mail content into specific content template
	$content = _parseMailContent($vorlage_kurzbz, $vorlage_data);

	// Set overall main content into the sancho mail template
	$body = _parseMailContent(
		'Sancho_Mail_Template',
		array(
			'CID_header' => 'sancho_header',
			'CID_footer' => 'sancho_footer',
			'content' => $content
		)
	);

	// Send mail
	return $ci->maillib->send(
		$_from,
		$to,
		$subject,
		$body,
		'', // alias
		$cc,
		$bcc,
		'', // altMessage
		true, // bulk
		true, // autogenerated
		$embeddedImages
	);
}

/**
 * Replace variables in the mail content template with specific mail content data.
 * @param string $vorlage_kurzbz Name of the template for specific mail content.
 * @param array $vorlage_data Associative array with specific mail content varibales
 *  to be replaced in the content template.
 * @return string
 */
function _parseMailContent($vorlage_kurzbz, $vorlage_data)
{
	$ci =& get_instance();
	$ci->load->library('VorlageLib');

	$result = $ci->vorlagelib->loadVorlagetext($vorlage_kurzbz);

	if (isSuccess($result))
	{
		// If the text and the subject of the template are not empty
		if (is_array($result->retval) && count($result->retval) > 0 &&
			!isEmptyString($result->retval[0]->text))
		{
			// Parses template text
			return parseText($result->retval[0]->text, $vorlage_data);
		}
	}
}

